### ISSUE TITLE
Capture console output even without PlutoUI.with_terminal()

### ISSUE THREAD

**Issue by kellertuer** [rikhuijzer/PlutoStaticHTML.jl#104]
I noticed that Pluto 0.19.0 started to have green boxes for output on terminal even if one does not use `PlutoUI.with_terminal()` would it be possible to add support for this here as well? (See Screenshot of an example below)

<img width="609" alt="Screenshot 2022-04-24 at 14 34 49" src="https://user-images.githubusercontent.com/115566/164976757-f535415a-9164-42c1-9daa-4335810c60fd.png">

**Comment by rikhuijzer** [comment]
No. I think that that is a good idea. Those things clutter everything. For development it's nice, but for publishing websites it isn't.

**Comment by kellertuer** [comment]
That is, for sure, a reasonable design decision :)
