### ISSUE TITLE
Assertion Error on CI (not appearing on local run even in same environment

### ISSUE THREAD

**Issue by kellertuer** [rikhuijzer/PlutoStaticHTML.jl#122]
My docs are usually running quite fine. Today I added a notebook and now I am running into a very strange error

https://github.com/JuliaManifolds/Manopt.jl/runs/6828371248?check_suite_focus=true#step:4:899

```
ERROR: LoadError: AssertionError: Expected .jl file at /home/runner/work/Manopt.jl/Manopt.jl/docs/../examples/RobustPCA.jl
[899](https://github.com/JuliaManifolds/Manopt.jl/runs/6828371248?check_suite_focus=true#step:4:900)
Stacktrace:
[...]
```

The error even states that the file is a jl file but complains it is not?

The same make file runs fine even in the same activated environment on my local machine. What might this error be?

**Comment by kellertuer** [comment]
Ah, I have a first guess – capitalisation of filenames is ignored on Mac OS while in Linux it is not. So might have been a typo on the code on my side. Maybe one could improve the error message since it actually checks that the file exists (not that it is necessarily a `.jl` file).

**Comment by rikhuijzer** [comment]
Sounds like a good PR. Something like this? Can you send in a PR?
```julia
function is_jl_file(path)
     isfile(path) && return false
     _, ext = splitext(path)
    return string(ext)::String == "jl"
end

function _evaluate_file(bopts::BuildOptions, hopts::HTMLOptions, session, in_file, time_state)
    dir = bopts.dir
    in_path = joinpath(dir, in_file)::String
    @assert is_jl_file(in_path) "Expected .jl file at $in_path"
    [...]
end
```

**Comment by kellertuer** [comment]
That sounds like a good start but would still lead to maybe a confusion in my case (actually the one I stumbled upon.

Since I had a typo in my file name (actually the `R` in `Robust` is small in the filename but Mac OS does not care about that, Linux does), it would be better to actually report

```
File not found at $in_path
```

if the file does not exist. I will try to do a PR soon.
