### ISSUE TITLE
_convert_admonition throws type error with quoted Julia code inside

### ISSUE THREAD

**Issue by lf28** [rikhuijzer/PlutoStaticHTML.jl#132]
Hello there,

After a few testings, admonitions blocks with quoted code cannot be built properly. 

For example,

> md""
>!!! info "information"
>    \```julia
>        plot(1:10);
>    \```
>""

Note that the code block within the ``` are properly indented.

And `build_tutorials()` will throw type error like this 

> ERROR: TypeError: in typeassert, expected UnitRange{Int64}, got a value of type Nothing
Stacktrace:
  [1] _wrap_admonition_body(html::String)
    @ PlutoStaticHTML ~/.julia/packages/PlutoStaticHTML/7lLxj/src/style.jl:36

Have tested on Julia 1.8 and PlutoStaticHTML v5.0.13

**Comment by rikhuijzer** [comment]
This was probably fixed by https://github.com/rikhuijzer/PlutoStaticHTML.jl/pull/151

**Comment by rikhuijzer** [comment]
Sorry for delayed response by the way. It was a very fair bug report, also reported in https://github.com/rikhuijzer/PlutoStaticHTML.jl/issues/148#issuecomment-1276192535.
