### ISSUE TITLE
Hide code cell that is hidden in Pluto frontend

### ISSUE THREAD

**Issue by kellertuer** [rikhuijzer/PlutoStaticHTML.jl#149]
In Pluto you can hide code cells.

I did this for example with the code cells for #148 

However in the rendered Documenter file these cells show up. Would it be possible to not show these (similar to the markdown codes that are not shown)?

**Comment by rikhuijzer** [comment]
Have you tried putting `# hideall` in the code block? The output you can hide by returning `nothing` if I'm not mistaken

**Comment by rikhuijzer** [comment]
Oh wait this is about reading the front end logic. That would probably be a good idea yes. It should be a relatively easy PR since it is a field of `cell.hidden` or something like that

**Comment by kellertuer** [comment]
I did not find the `# hideall` keyword and that might be an (interims) solution; but yes, indeed – my idea was to read out whether a cell is hidden. My problem is, that I do not know Pluto internals well enough to do such a PR.

The output I did already hide – you just can do that as well with just a `;` at the end of the cell :)

**Comment by rikhuijzer** [comment]
> In Pluto you can hide code cells.
> 
> I did this for example with the code cells for #148
> 
> However in the rendered Documenter file these cells show up. Would it be possible to not show these (similar to the markdown codes that are not shown)?

Can you let me know which annotation in the `.jl` file you mean? I can only find `skip_as_script` and `disabled` when I modify notebooks and look at the file changes. I suspect that hiding the code block is not stored in the `.jl` file, so it also cannot be read by `PlutoStaticHTML`

**Comment by kellertuer** [comment]
I am not sure about how Pluto remembers that but if code cells are hidden, this is remembered. So I am not sure how this is annotated. I am really just a Pluto user not a developer.

**Comment by kellertuer** [comment]
So I am not sure, I just did a small test case: A notebook like

<img width="906" alt="Screenshot 2022-10-16 at 13 28 51" src="https://user-images.githubusercontent.com/115566/196032837-e7d6db4c-caf5-48c7-9c6a-64a63348148f.png">

(one hidden one non-hidden cell has the code

```Julia
### A Pluto.jl notebook ###
# v0.19.13

using Markdown
using InteractiveUtils

# ╔═╡ 76d9153a-4d45-11ed-330b-af64957bea95
a = 1

# ╔═╡ e10a7b29-c888-4af5-b4fa-92ed2a2a96b0
b = a+1

# ╔═╡ 00000000-0000-0000-0000-000000000001
PLUTO_PROJECT_TOML_CONTENTS = """
[deps]
"""

# ╔═╡ 00000000-0000-0000-0000-000000000002
PLUTO_MANIFEST_TOML_CONTENTS = """
# This file is machine-generated - editing it directly is not advised

julia_version = "1.8.1"
manifest_format = "2.0"
project_hash = "da39a3ee5e6b4b0d3255bfef95601890afd80709"

[deps]
"""

# ╔═╡ Cell order:
# ╟─76d9153a-4d45-11ed-330b-af64957bea95
# ╠═e10a7b29-c888-4af5-b4fa-92ed2a2a96b0
# ╟─00000000-0000-0000-0000-000000000001
# ╟─00000000-0000-0000-0000-000000000002
```

So I suspect that in the file it can be seen in the cell oder part, where `# ╟─` (note just one horizontal line) indicates hidden and `# ╠═` (note the double lines, though here on GitHub not so well rendered). I hope in Pluto itself it is stored more seeable?

**Comment by rikhuijzer** [comment]
Well spotted!

After writing your notebook to `tmp.jl`:

```julia
julia> using Pluto

julia> session = Pluto.ServerSession();

julia> nb = Pluto.SessionActions.open(session, "tmp.jl"; run_async=false);

julia> nb.cells[1].code_folded
true

julia> nb.cells[2].code_folded
false
```
I'll release a new version soon.
