### ISSUE TITLE
Show information on why cache is not used?

### ISSUE THREAD

**Issue by Dsantra92** [rikhuijzer/PlutoStaticHTML.jl#164]
This is along the lines of https://github.com/JuliaDocs/DemoCards.jl/issues/137 and https://github.com/rikhuijzer/PlutoStaticHTML.jl/issues/161. Developers face issue to identify why the cache present is not used: if it was the input sha or julia version used. Showing this little information will help to debug the cache functionality from CI.

**Comment by rikhuijzer** [comment]
Great suggestion! Why didn't I think of that. I'll do that soon. Probably later this week
