### ISSUE TITLE
How to include images that work in the notebook and the export

### ISSUE THREAD

**Issue by kellertuer** [rikhuijzer/PlutoStaticHTML.jl#22]
I saw in Pluto that it is best to load images with the load function from Images.jl.

This works fine in the notebook 

https://github.com/JuliaManifolds/Manopt.jl/blob/update-pluto-export/pluto/bezier.jl

when I run it locally – note especially lines like 

https://github.com/JuliaManifolds/Manopt.jl/blob/02895b47e24be38a0ebd47001f129620380ee1b8/pluto/Bezier.jl#L124

The image is included in the notebook when running; when one activates rendering (not on CI) then Asymptote is used to render it; here the images are checked in and are found (without rendering) at least locally.

In PlutoStaticHTML, I get the error

https://github.com/JuliaManifolds/Manopt.jl/runs/4398948388?check_suite_focus=true#step:4:806

would it be possible to display loaded images?

**Comment by rikhuijzer** [comment]
The error from the log is

```
ERROR: LoadError: Dict{Symbol, Any}(:msg => "syntax: extra token after end of expression\n\nBoundaries: [45, 58]", :stacktrace => Dict{Symbol, Any}[Dict(:call => "top-level scope", :inlined => false, :file => "none", :line => 1, :path => "none")])
```

This is a message passed inside Pluto meaning that the Pluto notebook execution failed. I'm closing this issue for now since it doesn't seem to be related to PlutoStaticHTML. Please reopen if you disagree.

**Comment by kellertuer** [comment]
Well, let‘s say: In the last commit the CI formatter recognises something and wanted to format the code which introduced a second line/command which made Pluto error on that one.

So the error you got was just the cell being destroyed by the formatter, the most recent one should error again on the image task. Sorry for that – I was already 2 hours into trying to get it work.

**Comment by rikhuijzer** [comment]
Could you give a bit more information on what is the image problem because I don’t understand it yet

Most image mine types (like plots) should be converted to an base64 encoded image and work thanks to that. This way it hacks around having to deal with file paths

**Comment by kellertuer** [comment]
Sure, sorry, I should have given more detail here.

I am using Asymptote (included in usual tex distributions) to render the images, this command

https://github.com/JuliaManifolds/Manopt.jl/blob/02895b47e24be38a0ebd47001f129620380ee1b8/pluto/Bezier.jl#L96

generates the asy file, and this

https://github.com/JuliaManifolds/Manopt.jl/blob/02895b47e24be38a0ebd47001f129620380ee1b8/pluto/Bezier.jl#L117

renders. On the CI I do not have a LaTeX distribution (or I am to lazy to get one), so I have a switch that does not run the rendering.

Anyways in both cases a png is created, which I load here

https://github.com/JuliaManifolds/Manopt.jl/blob/02895b47e24be38a0ebd47001f129620380ee1b8/pluto/Bezier.jl#L124

into base64, since that was what I saw worked in notebooks.

So the problem is indeed a problem with file paths, yes.

**Comment by rikhuijzer** [comment]
> On the CI I do not have a LaTeX distribution (or I am to lazy to get one), so I have a switch that does not run the rendering.

This sounds very complex to manage because it means writing code locally and debugging in CI. How about installing LaTeX in CI? For example, I've been using something like the code below for a while:

```
    - name: Install LaTeX
      run: |
        sudo apt-get -qq update
        # Don't make this a fancy multiline thing which is hard to debug on the runner.
        sudo apt-get install -y pdf2svg
        sudo apt-get install -y texlive-latex-base
        sudo apt-get install -y texlive-binaries
        # Includes Tikz.
        sudo apt-get install -y texlive-pictures
        sudo apt-get install -y texlive-latex-extra
        # In response to error luatex85.sty not found.
        sudo apt-get install -y texlive-luatex
```

**Comment by kellertuer** [comment]
But even using LaTeX in the CI the asymptote would write a PNG to the file. Would that help?

**Comment by rikhuijzer** [comment]
> But even using LaTeX in the CI the asymptote would write a PNG to the file. Would that help?

Ah. So it also doesn't work locally? It is possible to write an image to a file and render that but it's usually tricky because there is a difference between the file path en the online URL path. Also, it requires ensuring that the file ends up in a public directory on the server.

Would it be possible to solve it via
```
# hideall
Images.load(path_to_png)
```

**Comment by kellertuer** [comment]
Yes, running documenter also does not work locally, since it can not load the saved png.

I do not understand your solution there, the goal is to have the image in the final html page.

**Comment by rikhuijzer** [comment]
> I do not understand your solution there, the goal is to have the image in the final html page.

![image](https://user-images.githubusercontent.com/20724914/144574805-a576cf79-043f-46f1-a3dd-8846af8de50b.png)

If the image is shown in Pluto, then it will be shown in the final HTML page too.

**Comment by kellertuer** [comment]
It is shown in pluto (but loaded from same file not from URL), but not in local or CI HTML conversion. So the problem _is_ loading the file and Asymptote _only_ writes to disc (since it is a command line tool).

**Comment by rikhuijzer** [comment]
> Asymptote only writes to disc

And `load` can read a file from disk. The idea is that you know the path to the image inside Pluto and use `load` to show it. Then PlutoStaticHTML will handle the rest.

**Comment by kellertuer** [comment]
I know the (relative) path from the original pluto notebook to the file in the repo ( it works in Pluto), just not from your temp folder, when you run the notebook.

**Comment by rikhuijzer** [comment]
> just not from your temp folder, when you run the notebook.

My temp folder?

**Comment by kellertuer** [comment]
I have to check the error message again (in one go the logs) it stated that the HTML war running in some `tmp/`subfolder? I will check the error messages again, or it is that it is run from the make file (and that is in a different folder than the Pluto notebook).

**Comment by kellertuer** [comment]
Here this

https://github.com/JuliaManifolds/Manopt.jl/runs/4399900505?check_suite_focus=true#step:4:805

is nearly the right path up to the `tmp/` upfront the `bezier/...` in the error message. I locally do not have tmp and I do not know how that ends in up there – unless the Rendering is run in a tmp folder?

**Comment by rikhuijzer** [comment]
Try to get an absolute path. Usually more reliable anyway

**Comment by kellertuer** [comment]
How would I do that? currently the image is in the `bezier` subfolder of the `pluto` folder of the repo. But an absolut path would be `/Users/ronny/Repositories/Julia/Manopt.jl/pluto/bezier/` and that would definitively not exist on CI ;)

**Comment by kellertuer** [comment]
to be precise my current approach uses `@__DIR__` and hence is basically an absolute path. Just the wrong one when running PlutoStaticHTML somehow

**Comment by rikhuijzer** [comment]
Manopt.jl does exist in CI because it clones the repo. Would
`joinpath(pkgdir(Manopt), "pluto", "bezier"` work?

**Comment by kellertuer** [comment]
I will check, first for completeness,

on my machine: I set the path using `image_prefix = String(@__DIR__) * "/bezier"` (i.e. in a subfolder of the place where the notebook itself is)
* (works) Running Pluto itself the path gets set to `~/Repositories/Julia/Manopt.jl/pluto/bezier`
* (works) Running the notebook using `include` sets the path to `~/Repositories/Julia/Manopt.jl/pluto/bezier`
* (does not work) Running `docs/make.jl` and hence PlutoStaticHTML locally sets the path to `/var/folders/_v/wg192lpd3mb1lp55zz7drpcw0000gn/T/bezier`
* (does not work) Running on `make.jl` on CI sets it to `/tmp/bezier` (that's what I meant above with temp dir)

Using your proposed approach yields
* (does not work) As a Pluto Notebook run in Pluto `~/.julia/packages/Manopt/rcbsQ/pluto/bezier` (since it uses the Package Manager and not the local version) and hence fails (since I only have the images on the new branch)
* (works) Running the notebook using `include` sets the path to `~/Repositories/Julia/Manopt.jl/pluto/bezier` (since that is in global environment)
* (does not work) Running `docs/make.jl` yields the folder ``~/.julia/packages/Manopt/rcbsQ/pluto/bezier` and hence also does not work (on Manopt.jl#master see two points above)
* (does not work) Running `docs/make.jl`in CI behaves as the first and third case here and uses `/home/runner/.julia/packages/Manopt/rcbsQ/pluto/bezier` so it might work on current release commits.

**Comment by kellertuer** [comment]
Another variant that works with the first two (in Pluto and REPL) but not in `make.jl` (or CI) is

```
    localpath = join(splitpath(@__FILE__)[1:(end - 1)], "/") # remove file to get files folder
    image_prefix = localpath * "/bezier"
```

This was my last idea on how to maybe access these.

**Comment by rikhuijzer** [comment]
> `image_prefix = String(@__DIR__) * "/bezier"`

In general, use `joinpath(@__DIR__, "bezier")`. Manual string concatenations are not platform independent and require manual ensuring that the forward slash is appropriately added in between.

So, I see that the path is indeed absolute via `image_prefix` so that isn't the problem.

Maybe a stupid question, but is `render_asy` set to `true` in CI? Otherwise, it will locally work due to the images being available from the last time, but not online because the images need to be rendered still.

**Comment by kellertuer** [comment]
If I set render_asy to true in the CI I would also have to install TeX there and stuff, but it would also not help for the last two images - since they are results of a large experiment that would run longer than GitHub allows me to run the CI.

**Comment by fonsp** [comment]
You can also use `PlutoUI.LocalResource("../images/hello.png")`, it does the base64 trick automatically. Images.jl is a very large package, so it might be nicer to avoid.

**Comment by kellertuer** [comment]
I will try, but the main problem seems to be that the rendering here takes place in a different folder such that relative paths won‘t work (and absolute ones neither).

**Comment by kellertuer** [comment]
Sadly the idea of `PlutoUI` does not even work locally, I get

```bash
      From worker 3:    [ Info: //var/folders/_v/wg192lpd3mb1lp55zz7drpcw0000gn/T/bezier
      From worker 3:    ┌ Warning: `LocalResource` **will not work** when you share the script/notebook with someone else, _unless they have those resources at exactly the same location on their file system_. 
      From worker 3:    │ 
      From worker 3:    │ ## Recommended alternatives (images)
      From worker 3:    │ 1. Go to [imgur.com](https://imgur.com) and drag&drop the image to the page. Right click on the image, and select "Copy image location". You can now use the image like so: `PlutoUI.Resource("https://i.imgur.com/SAzsMMA.jpg")`.
      From worker 3:    │ 2. If your notebook is part of a git repository, place the image in the repository and use a relative path: `PlutoUI.LocalResource("../images/cat.jpg")`.
      From worker 3:    └ @ PlutoUI ~/.julia/packages/PlutoUI/iqFqj/src/Resource.jl:80
      From worker 3:    ┌ Warning: `LocalResource` **will not work** when you share the script/notebook with someone else, _unless they have those resources at exactly the same location on their file system_. 
```

and then  an error
```
ERROR: LoadError: Dict{Symbol, Any}(:msg => "SystemError: opening file \"//var/folders/_v/wg192lpd3mb1lp55zz7drpcw0000gn/T/bezier/Casteljau-illustr.png\": No such file or directory", :stacktrace => Dict{Symbol, Any}[Dict(:call => "var\"#systemerror#69\"(::Nothing, ::typeof(systemerror), ::String, ::Int32)", :inlined => false, :file => "error.jl", :line => 174, :path => "./error.jl"), Dict(:call => "#systemerror#68", :inlined => true, :file => "error.jl", :line => 173, :path => "./error.jl"), Dict(:call => "systemerror", :inlined => true, :file => "error.jl", :line => 173, :path => "./error.jl"), Dict(:call => "var\"#open#636\"(::Bool, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::typeof(open), ::String)", :inlined => false, :file => "iostream.jl", :line => 293, :path => "./iostream.jl"), Dict(:call => "open", :inlined => true, :file => "iostream.jl", :line => 282, :path => "./iostream.jl"), Dict(:call => "var\"#open#355\"(::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, ::typeof(open), ::Base.var\"#362#363\"{Tuple{}}, ::String)", :inlined => false, :file => "io.jl", :line => 328, :path => "./io.jl"), Dict(:call => "open", :inlined => true, :file => "io.jl", :line => 328, :path => "./io.jl"), Dict(:call => "read", :inlined => true, :file => "io.jl", :line => 434, :path => "./io.jl"), Dict(:call => "LocalResource(::String)", :inlined => false, :file => "Resource.jl", :line => 86, :path => "/Users/ronnber/.julia/packages/PlutoUI/iqFqj/src/Resource.jl"), Dict(:call => "top-level scope", :inlined => true, :file => "jl_p5g7GI#==#38b8f8af-ba81-4d3b-83b7-56b0d41ea708", :line => 1, :path => "/var/folders/_v/wg192lpd3mb1lp55zz7drpcw0000gn/T/jl_p5g7GI#==#38b8f8af-ba81-4d3b-83b7-56b0d41ea708")])
```

so compared to `load` (which at least works locally)  `LocalResource` does not even work locally, but yields warnings that seem to indicate that the error from above will persist on CI.
