### ISSUE TITLE
Feature Request - Links to download the original notebook and run the Original notebook in Binder

### ISSUE THREAD

**Issue by VarLad** [rikhuijzer/PlutoStaticHTML.jl#25]
It'd be nice if the user had the option to embed the links to download the original notebook or open it in Binder, in Documenter and if possible, Franklin

I'm making this issue for an open discussion on this topic :)

**Comment by rikhuijzer** [comment]
This package doesn’t make any assumptions about where the notebook is located, so adding those links will be quite difficult. Maybe, we could do one helper function which takes some arguments and returns the appropriate local and web paths. What do you think?

**Comment by VarLad** [comment]
Sounds neat!

**Comment by rikhuijzer** [comment]
In general, adding a link is already reasonably easy by the way. In Franklin, I use:

```julia
"""
    lx_readhtml(com, _)

Embed a Pluto notebook via:
https://github.com/rikhuijzer/PlutoStaticHTML.jl
"""
function lx_readhtml(com, _)
    file = string(Franklin.content(com.braces[1]))::String
    dir = joinpath("posts", "notebooks")
    html_path = joinpath(dir, "$file.html")
    jl_path = joinpath(dir, "$file.jl")

    return """
        ```julia:pluto
        # hideall

        using PlutoStaticHTML: notebook2html

        path = "$html_path"
        html = read(path, String)
        println("~~~\n\$html\n~~~\n")
        println("_To run this blog post locally, open [this notebook](/$jl_path) with Pluto.jl._")
        ```
        \\textoutput{pluto}
        """
end
```

Also, this package can add build context with

```julia
append_build_context = true
parallel_build!(dir; append_build_context)
```

Together, the bottom of my blog posts now look like, [for example](https://huijzer.xyz/posts/latent/):

```
Built with Julia 1.6.4 and

Bijectors 0.9.11
CairoMakie 0.6.6
DataFrames 1.2.2
StableRNGs 1.0.0
Turing 0.19.0

To run this blog post locally, open this notebook with Pluto.jl.
```

**Comment by VarLad** [comment]
Thanks for the example! 
I guess the same can easily be done for Documenter? (and if possible, the link at the top with a badge like the following? This is from Literate.jl)

![image](https://user-images.githubusercontent.com/51269425/148054329-28f35537-c7b9-4132-875a-b4cd154185df.png)

**Comment by rikhuijzer** [comment]
> I guess the same can easily be done for Documenter?

Yes it should be quite easy to do something similar for Documenter.jl. You just need to figure out what the path of the file is online, but that should be doable with some trial and error

**Comment by rikhuijzer** [comment]
I'll leave this functionality to be implemented at the user-side. This package doesn't make assumptions where the HTML is stored. Adding a Binder link is too specific.

**Comment by VarLad** [comment]
@rikhuijzer I agree to that  
The best way to go forward with this is probably a simple example which involves Documenter

I'll try looking into it later. If someone else could provide such an example in the mean time, that would be heavily appreciated.
