### ISSUE TITLE
Render formulae from Pluto Notebook in Documenter export/use.

### ISSUE THREAD

**Issue by kellertuer** [rikhuijzer/PlutoStaticHTML.jl#3]
I a cell contains markdown with a formula (non-inline) like

````
md"""
We can generalise the notion of a directional derivative, i.e. for the “direction” ``Y∈T_p\mathcal M`` let ``c\colon [-ε,ε]``, ``ε>0``, be a curve with ``c(0) = p``, ``\dot c(0) = Y`` and we obtain
```math
	Df(p)[Y] = \frac{\mathrm{d}}{\mathrm{d}t} f(c(t)) = \lim_{h \to 0} \frac{1}{h}(f(\exp_p(hY))-f(p))
```
"""
````

and one uses the (otherwise really nice) idea from the `docs/make.jl` in this repository,
the inline math is rendered but the formula is not. 

I tried quite a few things, the Franklin example from the docs (in the generated markdown raw html part) and several other approaches but though Documenter loads both latex as well as auto-render I am not able to trigger them, even not with copying the require approach from `documenter.js`.

**Comment by kellertuer** [comment]
I finally found the time to check the new (registered) version and the problem persists locally at least.
Here is a manual trick export by Pluto itself (current version in the docs)

https://manoptjl.org/stable/pluto/AutomaticDifferentiation.html

and I switched to the variant described in the makefile here, see 

https://github.com/JuliaManifolds/Manopt.jl/blob/3fca79067927253a109706398c864576fb07106b/docs/make.jl#L57

Currently even with a manual attempt trying to render the math formulae manually (line 71-85 same file). With those lines, no math gets rendered, without only inline get rendered but the others are just plain
```
$$ mathformula $$
```
lines shown in the final HTML, so they do not get rendered. With the script, the ``$$`` vanish but there is nothing rendered. Interestingly while the log looks the same as locally the resulting page looks fine

https://manoptjl.org/previews/PR98/pluto/AutomaticDifferentiation.html

So I have to check what is different between GH Actions and my local version (currently for example that I am on a fresh Julia 1.7 and GH is on 1.6.4).

PS: There is also one warning (ignore the errors after that I might have broken one of my Literate examples)
https://github.com/JuliaManifolds/Manopt.jl/runs/4379719470?check_suite_focus=true#step:4:951

**Comment by kellertuer** [comment]
Update: So with the CI being on 1.7 I can reproduce the error in the CI (see the PR998/ link above), the corresponding PR is of course https://github.com/JuliaManifolds/Manopt.jl/pull/98

**Comment by rikhuijzer** [comment]
Pluto.jl uses MathJax, so the most reliable method would probably to use that math engine.

Luckily, Documenter.jl allows configuring the math engine:

```
using Documenter: HTML, MathJax3, makedocs

mathengine = MathJax3()
format = HTML(; mathengine, [...])
makedocs(; format, [...])
```

**Comment by kellertuer** [comment]
I was shortly confused by the `append_build_context`which I do not have on master but also I do not need. Locally it worked.

If you want you could add to the raw html documenter export something like 

https://github.com/JuliaManifolds/Manopt.jl/blob/00aa4a8f833b4052bfa97ca8bcf7956c3286639c/docs/make.jl#L62-L64

to get the GitHub icon correct (of course you have to adapt the interpolation to your variables of the Pluto notebook path and filename).

**Comment by rikhuijzer** [comment]
> If you want you could add to the raw html documenter export something like

Awesome tip.

**Comment by kellertuer** [comment]
...and after allowing the newest Documenter version it also works on CI, so the `MathJax3()` works like a charm now - great! I just have to maybe color the frames of the code cells (input/output) a little differently.
I also noticed that output is bash-style – maybe using Julia here would also be good?

**Comment by rikhuijzer** [comment]
> I also noticed that output is bash-style – maybe using Julia here would also be good?

The output style is inferred by Highlight.js, if I'm not mistaken. This is the output block:

https://github.com/rikhuijzer/PlutoStaticHTML.jl/blob/52418b3087c54046129bb24e6c1078f4adf3dc8d/src/html.jl#L37-L42

Output can be anything as well as RAW text sometimes, so setting it to Julia will also give problems IMO

**Comment by rikhuijzer** [comment]
> ...and after allowing the newest Documenter version it also works on CI, so the MathJax3() works like a charm now - great!
