### ISSUE TITLE
Use Pluto.SessionActions to open / close a notebook

### ISSUE THREAD

**Issue by fonsp** [rikhuijzer/PlutoStaticHTML.jl#5]
Hi!

We don't really have public API, but `Pluto.SessionActions` is the closest you can get! It gives easy function to open, run and shut down a notebook. These functions will probably not change for a long time. Take a look!

-fons

**Comment by rikhuijzer** [comment]
Awesome :smile: Thank you for thinking with me. I'll look into it soon

**Comment by AbhimanyuAryan** [comment]
@rikhuijzer in my case also I want to use `Pluto SessionActions` and have the functionality to export cells in static html with PlutoStaticHTML `update_run!(session, notebook, cells)` for some reason is causing lot of scoping issues.
