### ISSUE TITLE
Disable the complex Julia objects in Pluto

### ISSUE THREAD

**Issue by rikhuijzer** [rikhuijzer/PlutoStaticHTML.jl#53]
```julia
begin
    if false
        # To ensure that this cell runs first.
        import Pkg
    end
    # filter!(m -> !occursin("pluto", string(m)), PlutoRunner.allmimes)
    PlutoRunner.use_tree_viewer_for_struct(x) = false
end
```

EDIT: The problem of this is that it will automatically trigger the nbpkg environment :\. So, I need to think a bit more on how to solve this properly. Note that simply defining method overrides isn't possible because Pluto spawns new processes. For now, let's stick to the current implementation.

EDIT2: Maybe add a cell and manually set some cell metadata causing it to be executed first?

**Comment by rikhuijzer** [comment]
This cell will be most important

```julia
    if false
        import Pkg
    end
```

because `if :Pkg \in top.definitions` in `topological_order.jl`

**Comment by rikhuijzer** [comment]
`nb.cells_dict` != topological order

**Comment by AbhimanyuAryan** [comment]
thanks 👍
