### ISSUE TITLE
doesn't hide the hidden cells in Pluto notebook 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [rikhuijzer/PlutoStaticHTML.jl#6]
I have couple of hidden cells in Pluto notebook. Like `chown`, `touch`, `write` operations. For which I definitely want to show the output but not show the `cell` itself to end user

Earlier I was using Pluto static `html` export but because Pluto doesn't export cells based html in body(it populates body using Javascript `<script>`), it's not good for SEO which got me interested in PlutoStaticHTML.jl

**Comment by rikhuijzer** [comment]
I don't think that Pluto stores whether a cell should be hidden or visible in the notebook file, does it? If you re-open a notebook with hidden cells, all are visible again.

What I did implement is a `# hideall`. You can add `# hideall` to your code block which will hide the code.

**Comment by AbhimanyuAryan** [comment]
> I don't think that Pluto stores whether a cell should be hidden or visible in the notebook file, does it? If you re-open a notebook with hidden cells, all are visible again.
> 
> What I did implement is a `# hideall`. You can add `# hideall` to your code block which will hide the code.

sure thanks. Let me try this

**Comment by AbhimanyuAryan** [comment]
ok yes `# hideall` works
