### ISSUE TITLE
Documentation a little hard to read.

### ISSUE THREAD

**Issue by kellertuer** [rikhuijzer/PlutoStaticHTML.jl#68]
In my previous try I had a for loop running
`html = notebook2html(pluto_file)`

and then wrote the string to a html file in the docs folder.

My puto notebooks lie in the folder `pluto/`, my docs lie in `docs`,...

So if I read the docs correncly I should call something like

```
pluto_src_folder = joinpath(@__DIR__, "..", "pluto/")
pluto_output_folder = joinpath(@__DIR__, "src/", "pluto/")
pluto_relative_path = "pluto/"
mkpath(pluto_output_folder)
#
#
# Please do not use the same name as for a(n old) literate Tutorial
pluto_files = ["Benchmark", "Bezier", "AutomaticDifferentiation"]
parallel_build(BuildOptions(pluto_relative_path, output_format=documenter_output)
```
?
This is a little hard to decipher what to actually call and where the md files will land in the docs. Maybe this could be improved? Currently I can not get the md export to run.

For example the output-format – I had it quite some time in the `parallel_run` until I saw in the source code but not in the docs that this should be in the Build options? Maybe each of the sections could have a small example code how to generate Documenter / Franklin / ... files in the concrete case.

**Comment by rikhuijzer** [comment]
Have you taken a look at the example projects linked in the [Documenter.jl section of the docs](https://rikhuijzer.github.io/PlutoStaticHTML.jl/dev/#Documenter.jl)?

I'm a bit hesitant to add too much code in the docs because it hard to keep them up to date and it is hard to describe what code needs to be put in what file. The [`docs/make.jl](https://github.com/rikhuijzer/Resample.jl/blob/main/docs/make.jl) at Resample.jl should be pretty clear.

**Comment by kellertuer** [comment]
Well, it took me about an hour and it seems something like

```
pluto_src_folder = joinpath(@__DIR__, "..", "pluto/")
pluto_files = ["Benchmark", "Bezier", "AutomaticDifferentiation"]
parallel_build(BuildOptions(pluto_src_folder, output_format=documenter_output), [ "$p.jl" for p in pluto_files]);
```

seems to work (I see output that they are build) – but I can't see where they are written to. so I am not sure how to set up the menu?

And with an example I just mean a few lines like the 3 above. Especially that the output_format should go into the build options is well hidden – at least for me.
Step 3 in the API says to set the output-format but not where, Documenter section states to set it to what but not where. I had to check the code to find _where_ to set that option.

**Comment by kellertuer** [comment]
In my old code I set the menu entries automatically like

```
pluto_files = ["Benchmark", "Bezier", "AutomaticDifferentiation"]
pluto_titles = ["speed up! using `gradF!`", "Use Bezier Curves", "AD in Manopt"]
# build menu.
for (i, f) in enumerate(pluto_files)
    global TutorialMenu
    @info "Building Pluto Notebook $f.jl"
    pluto_file = pluto_src_folder * f * ".jl"
    push!(TutorialMenu, pluto_titles[i] => joinpath(pluto_relative_path, f * ".md"))
end
```

but currently no files are generated so I do not know where to link to?

**Comment by kellertuer** [comment]
(Sorry for again so many questions, but I really just read the docs and the source code for about an hour to get any non-error run from make.jl).

**Comment by rikhuijzer** [comment]
Ah for multiple files! Yes sorry then you need [`TuringGLM.jl/docs/make.jl`](https://github.com/TuringLang/TuringGLM.jl/blob/main/docs/make.jl). Can you see whether that helps?

**Comment by kellertuer** [comment]
how do I do single ones? I read parallel build as it is _only_ for multiple files? I think that's why I used `notebook2html`before but I am not sure that exists? At least the docs never mentioned this nor could I find something like that for markdown in the source.

**Comment by kellertuer** [comment]
Hm Where does TuringGLM build Pluto notebooks?

**Comment by kellertuer** [comment]
Ah.

Well – the new stuff works already better than my last approach. Here's what I will stop for not with

```pluto_files = ["Benchmark", "Bezier", "AutomaticDifferentiation"]
pluto_titles = ["speed up! using `gradF!`", "Use Bezier Curves", "AD in Manopt"]
files = parallel_build(
    BuildOptions(pluto_src_folder, output_format=documenter_output, write_files=false),
    [ "$p.jl" for p in pluto_files]
);
# build menu and write files myself - tp set edit url correctly.
for (i, f) in enumerate(pluto_files)
    global TutorialMenu
    pluto_file = pluto_src_folder * f * ".jl"
    write(
        pluto_output_folder * f * ".md",
        """
        ```@meta
        EditURL = "$(pluto_src_folder)$(f).jl"
        ```

        $(files[i])

        """,
    )
    push!(TutorialMenu, pluto_titles[i] => joinpath(pluto_relative_path, f * ".md"))
end
```

Some explicit example like this would be nice in the docs – sure mine is a little anvanced, since I already set the edit url - and the result looks nice and has dark mode (woohow). Just no menu yet, but I am getting somewhere :)

<img width="1284" alt="Bildschirmfoto 2022-02-12 um 12 00 11" src="https://user-images.githubusercontent.com/115566/153708700-259d5876-1b91-4c32-a54b-21b633b068ac.png">

**Comment by kellertuer** [comment]
But some code like this or even a small sorter one (writing out the files and not like me taking the strings and writing them out myself) would be great in the docs.

**Comment by kellertuer** [comment]
So, now also the menu builds and it looks quite nice!

The code I endet up with for now is
```
pluto_files = ["Benchmark", "Bezier", "AutomaticDifferentiation"]
pluto_titles = ["speed up! using `gradF!`", "Use Bezier Curves", "AD in Manopt"]
# build menu and write files myself - tp set edit url correctly.
for (i, f) in enumerate(pluto_files)
    global TutorialMenu
    rendered = parallel_build( #though not really parallel here
        BuildOptions(pluto_src_folder, output_format=documenter_output, write_files=false),
        [ "$(f).jl"]
    );
    write(
        pluto_output_folder * f * ".md",
        """
        ```@meta
        EditURL = "$(pluto_src_folder)$(f).jl"
        ```

        $(rendered[1])
        """,
    )
    push!(TutorialMenu, pluto_titles[i] => joinpath(pluto_relative_path, f * ".md"))
end
```
And the result looks really neat now!

<img width="1126" alt="Bildschirmfoto 2022-02-12 um 12 17 25" src="https://user-images.githubusercontent.com/115566/153709132-2f4b0dec-71c2-4553-b53e-d20c90ddd392.png">

Thanks for the update – and as the title here says, maybe we could check how to improve the docs. If I find time I'll propose something.

**Comment by rikhuijzer** [comment]
> And the result looks really neat now!

Awesome!

> Thanks for the update – and as the title here says, maybe we could check how to improve the docs. If I find time I'll propose something.

Maybe we can add a link to your repository as an example too? A bit similar to <https://juliadocs.github.io/Documenter.jl/stable/man/examples/>.

**Comment by rikhuijzer** [comment]
I think you can speed up the build by using `use_distributed=false` by the way. Or do you need every notebook to spawn in a new process? The benefit of `use_distributed=false` is that you can avoid recompiling everything from scratch for each notebook. The drawback is that things become slightly less reproducible. For example, overriding a function in one notebook could affect the output in another. That being said, Documenter and Franklin of course evaluate everything in the same process too. If the notebooks don't do crazy overrides or other global stuff then it should be fine

**Comment by kellertuer** [comment]
> Maybe we can add a link to your repository as an example too? A bit similar to https://juliadocs.github.io/Documenter.jl/stable/man/examples/.

I currently have 3 of my 9 tutorials in Pluto notebooks (by the way even including images seems to work fine, I just have to check that this works on CI as well). So I'll give you a note once the tutorials are all in Pluto and that version is on the main branch.

> I think you can speed up the build by using use_distributed=false by the way. 

I saw that – currently I do not mind them talking a little longer and just feeling a little more safe :)

**Comment by kellertuer** [comment]
It does not work on CI (yet) though: https://github.com/JuliaManifolds/Manopt.jl/runs/5167126027?check_suite_focus=true#step:4:820 – works locally and has that exported and the versions match. Will continue somewhen later.

**Comment by kellertuer** [comment]
I noticed three points - are they worth their own issue?

1. In Pluto there is the nice `with_terminal()` that captures terminal output and renders it to the output cell. This seems to currently not work here?
2. recently Pluto switched to displaying warnings in the document – I do not mind here since the warning I have is with loading an image from the same folder – but they are also not displayed in the export
3. when I call `make("docs/make.jl") from the package base folder – I and up being in the folder of the Pluto notebooks (`pluto/`) after running make docs – this is not much of a bug just a little unexpected.

**Comment by kellertuer** [comment]
> > 1. In Pluto there is the nice with_terminal() that captures terminal output and renders it to the output cell. This seems to currently not work here?
> 
> Worth a separate issue

Ok, will do that.

> > 3. when I call make("docs/make.jl") from the package base folder – I and up being in the folder of the Pluto notebooks (pluto/) after running make docs – this is not much of a bug just a little unexpected.
> 
> I don't understand

I have the following structure
* `docs/` the documentation (sure)
* `pluto/` the notebooks.

now from within make I run the code mentioned above to generate the md files and continue to generate the docs.

But _running_ `parallel_build` seems to change the folder I am in:
1. I run `include("docs/make.jl")` from the base folder of my package.
2. usually after the run I execute `; open docs/build/index.html` in REPL to open the docs in my browser.
3. this does not work when running the exhorts, since then I am not in the package base folder anymore but in `pluto/` – so running the code mentioned above (within `make.jl` seems to switch to the folder the notebooks are in.

this is not that much a bug - the export and such works fine – just not behaviour I would expect.

**Comment by kellertuer** [comment]
With those being marked as issues, I think this can be closed.
