### ISSUE TITLE
`parallel_build` changes `pwd`

### ISSUE THREAD

**Issue by rikhuijzer** [rikhuijzer/PlutoStaticHTML.jl#69]
_running_ `parallel_build` seems to change the folder I am in:

_Originally posted by @kellertuer in https://github.com/rikhuijzer/PlutoStaticHTML.jl/issues/68#issuecomment-1037305221_

**Comment by rikhuijzer** [comment]
I was able to reproduce this and this only seems to hold when `use_distributed=false`.

**Comment by kellertuer** [comment]
At least I only noticed it there, yes.

**Comment by kellertuer** [comment]
I can report that my script runs fine in Pluto 4.0.4 :)
