### ISSUE TITLE
`with_terminal()` doesn't work

### ISSUE THREAD

**Issue by rikhuijzer** [rikhuijzer/PlutoStaticHTML.jl#70]
In Pluto there is the nice with_terminal() that captures terminal output and renders it to the output cell. This seems to currently not work here?

_Originally posted by @kellertuer in https://github.com/rikhuijzer/PlutoStaticHTML.jl/issues/68#issuecomment-1037305221_

**Comment by rikhuijzer** [comment]
Fixed now @kellertuer

**Comment by kellertuer** [comment]
Nice! I will take a look soon. Together with the resolved pwd-iddue It might be that my notebooks should now work fine in the docs. Very cool.

**Comment by kellertuer** [comment]
I finally had the time to check – and it works like a charm. I still have to finish the last (but shorter) 4 tutorials, but I think I am now in a state that it works fine. Thanks for all the fixes :)
