### ISSUE TITLE
build crashes if a cell errors

### ISSUE THREAD

**Issue by rkurchin** [rikhuijzer/PlutoStaticHTML.jl#73]
Thanks for an awesome package, this is perfect for integrating code into my docs site, and way less fiddly than trying to do everything with doctests.

I'm using this to make a tutorial/demo for how to use my package and I was hoping to show how a particular thing throws an error and how to do it correctly, but it seems that as soon as an error is thrown in the evaluation, the build stops rather than finishing. Is there a way to force it to forge ahead anyway?

(For the moment I've just put that cell inside a `try-catch` and then `@show` the caught error which is a reasonable interim solution, but does look slightly clunkier - point being this is by no means an urgent thing to address)

**Comment by rikhuijzer** [comment]
> Thanks for an awesome package, this is perfect for integrating code into my docs site, and way less fiddly than trying to do everything with doctests.

Exactly my thoughts! Thank you for trying it out! :smile: 

> I'm using this to make a tutorial/demo for how to use my package and I was hoping to show how a particular thing throws an error and how to do it correctly, but it seems that as soon as an error is thrown in the evaluation, the build stops rather than finishing. Is there a way to force it to forge ahead anyway?
> 
> (For the moment I've just put that cell inside a try-catch and then @show the caught error which is a reasonable interim solution, but does look slightly clunkier - point being this is by no means an urgent thing to address)

I think that that is also what I would do. To hide the clunkiness from the reader, you can maybe use `# hide` comments at the end of lines that aren't interesting to the reader. Would that work? I've experimented a bit and this should work:

```julia
"Helper function to show error and stacktrace to the reader."
function error_and_stacktrace(e::Exception)
	trace = sprint(io -> Base.show_backtrace(io, backtrace()))
	err = sprint(showerror, e) |> Base.Text
	"""
	$err
	$trace
	"""
end
```

```julia
try # hide 
sum(1, 2)
catch e # hide
	error_and_stacktrace(e) |> Base.Text # hide
end # hide
```

![image](https://user-images.githubusercontent.com/20724914/154356262-99a73cfe-b51f-4015-bf35-4bc054896b53.png)

**Comment by rkurchin** [comment]
Ahh cool, didn't know about the `# hide` comment trick, thanks!

**Comment by rikhuijzer** [comment]
You're welcome

Can this issue be closed? :slightly_smiling_face:

**Comment by rkurchin** [comment]
Oh yeah, go ahead – sorry for delay replying to this!
