### ISSUE TITLE
Adding feature to switch between windows and linux/mac panels

### ISSUE THREAD

**Issue by AbhimanyuAryan** [rikhuijzer/PlutoStaticHTML.jl#76]
Rik this is more like a discussion than issue. I have been going through Django docs and noticed this command panel switching option based on OS
<img width="714" alt="win" src="https://user-images.githubusercontent.com/8083613/154888931-d9b9aa61-b530-4cf6-a747-343b59e2bae4.png">

<img width="714" alt="mac" src="https://user-images.githubusercontent.com/8083613/154888911-81c37c6c-48cc-4765-9443-a1ff43a258b2.png">

I was thinking it would be nice if we can parse this with PlutoSH and generate the corresponding html output(which then user can style with css however they want). If you think this feature makes sense I can go ahead look into possible implementation. Have something like this in mind. Lemme know

<img width="329" alt="feature" src="https://user-images.githubusercontent.com/8083613/154889176-dcd23756-af90-4be7-8d81-85b3ad48daa3.png">

**Comment by rikhuijzer** [comment]
Is this something that it possible to do inside Pluto? I think so via https://docs.julialang.org/en/v1/manual/handling-operating-system-variation/. You can add some `# hide` comments were needed.

**Comment by AbhimanyuAryan** [comment]
Hi, @rikhuijzer sorry for late reply. Rik not sure what if the code is sandwiched in markdown cell? Like as instruction 

start the server

md"""

Instructions to get the app started are below

```julia-repl
$ bin/repl.bat  # for windows
```

```julia-repl
$ bin/repl      # for Linux and Mac
```

visit localhost:8000

"""

**Comment by rikhuijzer** [comment]
That still sounds more like a Pluto problem. The notebook at https://github.com/JuliaPluto/weekly-call-notes/blob/main/2022/02-03/notes.jl has some HTML suggestions which might help.

**Comment by AbhimanyuAryan** [comment]
@rikhuijzer thanks for linking the example. I'll look into it 👍
