### ISSUE TITLE
BUG: renders html

### ISSUE THREAD

**Issue by AbhimanyuAryan** [rikhuijzer/PlutoStaticHTML.jl#9]
md"""

<triple-back-quotes>html

<triple-back-ticks/quotes>
"""

is rendered in html page. I should not. Should wrapper around <code></code>

![Screenshot 2021-11-05 at 2 09 38 PM](https://user-images.githubusercontent.com/8083613/140482585-ff722ef2-bcb6-4f5b-a7d5-27c243fcf72f.png)

**Comment by rikhuijzer** [comment]
Sorry I don't understand. Could you elaborate?

**Comment by rikhuijzer** [comment]
Ah, now I see. Just for my understanding. What is the use-case here? You are generating HTML to be displayed and want to show the code which you're using to display it?

Could you make a minimal example which I can run myself to see what happens?

**Comment by AbhimanyuAryan** [comment]
Sure will do tomorrow 😊

**Comment by AbhimanyuAryan** [comment]
put this in `runtests.jl`

```
@testset "Checking conversion" begin
    input=joinpath(@__DIR__,"demo.jl")
    html_contents = notebook2html(input)
    write("$(input)2.html", html_contents)

end
```

`demo.jl` below keep this in `test`

pkg> test

```
### A Pluto.jl notebook ###
# v0.17.1

using Markdown
using InteractiveUtils

# ╔═╡ 7ce16fc0-3f30-11ec-24d2-99c46898cadb
begin
	write("file.jl", """<h1 class="display-1 text-center">Watch tonight</h1>""")
end

# ╔═╡ Cell order:
# ╠═7ce16fc0-3f30-11ec-24d2-99c46898cadb
```

You see h1 is being rendered. It should not happen this way. Instead it should show `heading` in output. There should some way to not render code

![Screenshot 2021-11-07 at 12 16 24 AM](https://user-images.githubusercontent.com/8083613/140620563-bad9f532-fc71-4e49-8d79-62da8c564dfa.png)

**Comment by AbhimanyuAryan** [comment]
![Screenshot 2021-11-07 at 12 22 01 AM](https://user-images.githubusercontent.com/8083613/140620686-262cadb3-06df-4375-b529-382559a66e5b.png)

this renders just fine in Pluto html export

**Comment by rikhuijzer** [comment]
Currently, the code is wrapped via `code_block`, so that `"<b>foo</b>"` becomes:

```html
<pre>
<code>
<b>foo</b>
</code>
</pre>
```

Browsers will happily render this as a bold foo instead of `<b>foo</b>`.

This can be avoided by manually escaping the lower and great than symbols:

```
<pre>
<code>
&lt;b&gt;foo&lt/b&gt
</code>
</pre>
```

which will show in the browser as `<b>foo</b>`.

So, what do you think? Should we always escape these two symbols? Would that solve the issue and not cause other problems?

**Comment by AbhimanyuAryan** [comment]
> Currently, the code is wrapped via `code_block`, so that `"<b>foo</b>"` becomes:
> 
> ```html
> <pre>
> <code>
> <b>foo</b>
> </code>
> </pre>
> ```
> 
> Browsers will happily render this as a bold foo instead of literally showing `<b>foo</b>`.
> 
> This can be avoided by escaping the lower and great than symbols:
> 
> ```
> <pre>
> <code>
> &lt;b&gt;foo&lt/b&gt
> </code>
> </pre>
> ```
> 
> which will show in the browser as `<b>foo</b>`.
> 
> So, what do you think? Should we always escape these two symbols? Would that solve the issue and not cause other problems?

Yaa this should work go for it 🤘🏻
I'll pull once this is implemented and pushed to master. Will test the complete notebook. Than we can tag new version👌🏼

**Comment by rikhuijzer** [comment]
> I'll pull once this is implemented and pushed to master. Will test the complete notebook. Than we can tag new version👌🏼

https://github.com/rikhuijzer/PlutoStaticHTML.jl/commit/1cc70ed0fce642d08397980c73b9a21512a12d1b
